# config.py

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent

CAMERA_INDEX = 0
WINDOW_NAME = "Phone Attention Alert"

# YOLO
YOLO_MODEL_PATH = BASE_DIR / "yolov8s.pt"
PHONE_CONFIDENCE_THRESHOLD = 0.15
YOLO_IMAGE_SIZE = 960
MAX_PHONE_CANDIDATES = 3

# Logic
SUSPICIOUS_FRAMES_THRESHOLD = 10
PHONE_DIRECTION_MIN_COSINE = 0.20
PHONE_HORIZONTAL_OFFSET_THRESHOLD = 60
PHONE_VERTICAL_OFFSET_THRESHOLD = 35
HEAD_POSE_YAW_THRESHOLD = 7
HEAD_POSE_PITCH_THRESHOLD = 4
POSE_SMOOTHING_ALPHA = 0.35
ATTENTION_SMOOTHING_ALPHA = 0.4
TRACKER_MAX_MISSED_FRAMES = 12
